### ISSUE TITLE
question: uninstall faasd

### ISSUE THREAD

**Issue by mlunax** [openfaas/faasd#241]
I would like to ask what need to uninstall faasd from server.
Thanks in advance.

**Comment by alexellis** [comment]
See the dev guide so that you can stop the faasd and faasd-provider services. Then you can remove the binaries.

Effectively the reverse of the developer guide -> https://github.com/openfaas/faasd/blob/master/docs/DEV.md

@nitishkumar71 please could you add a section at the end on disabling what we install and how to remove it via `apt-get`?
