### ISSUE TITLE
Update all guides and cloud-config.txt to use release 0.9.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#81]
## Description

We need a volunteer to update all the guides, terraform automation and cloud-config.txt to use the release 0.9.0

The assets are in this repo, so you shouldn't have too hard of a time finding stuff. Bear in mind we now have a dependency on docker-compose.yaml and that may need to be downloaded before `faasd install`.

Feel free to ask questions here.

The new cloud-config.txt will need to be tested with evidence that it is using the new version - see `journalctl` for the logs which prints a version from faasd.

**Comment by sprive** [comment]
Questions about this...

1. What does "release `0.9.0`" refer to, exactly?
2. What check are you looking for, around `faasd install`?:
```
Nov 07 15:08:14 faasd cloud-init[1414]: Finding latest version from GitHub
Nov 07 15:08:17 faasd cloud-init[1414]: New version of faas-cli installed to /usr/local/bin
Nov 07 15:08:17 faasd cloud-init[1414]:  version: 0.15.2
```
3.  _"update all the guides"_... I've only exercised the one [MULTIPASS.md](https://github.com/openfaas/faasd/blob/master/docs/MULTIPASS.md).  So it may (or may not) be worth splitting this issue, or outlining a checklist of guide(s) within this issue because I can make a PR for Multipass docnow (hit issues, took notes). I just can't hazard a guess when I'd be able to go through most or all others as I just got this running.

**Comment by rgee0** [comment]
Unfortunately I think you may have been overtaken by events with this one.  The issue is now over two years old and the 0.9.0 work seems to have been undertaken in https://github.com/openfaas/faasd/commit/db5312158cbc8b9df156884634d7355a80ab7127

**Comment by sprive** [comment]
No worries. Cheers

**Comment by alexellis** [comment]
Closing, thanks both
