### ISSUE TITLE
How do we reduce duplication of installation steps?

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#94]
How do we reduce duplication of installation steps?

All of the below, along with additional steps in https://github.com/jsiebens/rpi-faasd duplicate installation steps for containerd, CNI and other components / files:

https://github.com/openfaas/faasd/blob/master/docs/bootstrap/digitalocean-terraform/cloud-config.tpl
https://github.com/openfaas/faasd/blob/master/docs/bootstrap/cloud-config.tpl
https://github.com/openfaas/faasd/blob/master/cloud-config.txt

I'd be interested in suggestions from the community.

What about a parameterised bash file, that each of the automation tools could use, perhaps with parameters where needed for things like the gateway password?

Any work we do here will also benefit RPi users, who currently need to run all the steps manually, or install cloud-init and then update the above templates.

https://blog.alexellis.io/faasd-for-lightweight-serverless/

**Comment by jsiebens** [comment]
A centralized bash script could already be a step forward. Installing containerd will be the most interesting part, because it is not available for every architecture (like armhf, arm64)

When I was working on the images, I was thinking about a similar tool like `inletsctl` or `k3sup`, a lightweight binary to install faasd.

Something else I noticed when creating the images: although one can simply download the faasd binary, you still have to clone the git repository to get some files, like the docker-compose.yml file. Is it an option to bundle all those files, together with the binary, in e.g. a zip artifact?

**Comment by mehyedes** [comment]
Having a platform-agnostic way to install faasd would be great, and I don't see any better way than a bash script at this point. That would be a great way to improve the installation experience.

I also agree with @jsiebens regarding the installation steps. Would be better if one can get all needed files without cloning the git repo.

Something else crossed my mind, we always need to keep updating the installation docs(or cloud-config templates) to fetch the latest version of faasd, would it possible to use a single link that always points to the latest faasd release? 🤔

**Comment by jsiebens** [comment]
@LucasRoesler has already done some work on embedding the config assets -> #78

**Comment by LucasRoesler** [comment]
It seems reasonable that `faasd` should know how to completely install itself.

Perhaps we can create a "staging" folder where all of the components need to install faasd are put. Then `faasd` can embed static assets and generate into this folder. Additionally, it can also have the download urls for the confirmed working dependencies, which it can also download into that folder.  The user can then modify or update any of the files/binaries in that folder and then faasd can install them to the the correct location.  Something like 

```sh
faasd generate/init
faasd install
```

or if someone just wants the default, e.g. for a demo, install can call generate automatically (if the folder is empty/doesn't exist), so just

```sh
faasd install
```

If you want more flexibility, you could allow some of the values (for example, the containerd version) via env variables of flags to the `generate/init` command

**Comment by jsiebens** [comment]
I've created a first bash script to install faasd: https://gist.github.com/jsiebens/d623dee59da35f5f28c03b49f057a772
Tested on latest Raspois, Ubuntu 16/18/20, Debian 10 and CentOS 7/8

For Debian 10, I had to use containerd 1.3.7
On CentOS 8, the script is working, but I'm having some troubles with running faasd.

arm64 is not yet supported, because a version of containerd is not yet available for that platform.

**Comment by alexellis** [comment]
Sorry I missed this. How about Caddy as a parameter override?
